comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

codecov:
  token: deae9e1f-ee2b-45fb-a095-ee90d9c2f299

language: R
sudo: false
cache: packages
after_success:
 - Rscript -e 'covr::codecov()'
